[project]
name = "az-anima-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rdkit>=2025.3.2",
    "requests>=2.32.3",
    "st-social-media-links>=0.1.5",
    "streamlit>=1.45.1",
]
